# File: 001-storage-class-test-pvc.yaml
# Description: Test PVC for verifying storage class functionality
#
# Usage: Used by verify-storage-class.sh to test storage class
# Note: This is a temporary resource that will be created and deleted during testing

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 1Gi 