# file: /mnt/urbalurbadisk/manifests/034-tempo-config.yaml
# Helm values for Tempo (official chart) with OTLP receiver configuration
#
# Description:
# - Configures Tempo with OTLP receivers for OpenTelemetry integration
# - Uses local filesystem storage for development
# - Enables both gRPC and HTTP OTLP endpoints
# - Configures ingress for Traefik access
#
# Usage:
#   helm upgrade --install tempo grafana/tempo \
#     --namespace monitoring --create-namespace \
#     --values manifests/034-tempo-config.yaml

# Tempo server configuration
tempo:
  # Server settings
  server:
    http_listen_port: 3100
    grpc_listen_port: 9095
  
  # Distributor configuration with OTLP receivers
  distributor:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
  
  # Ingester configuration
  ingester:
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
    max_block_duration: 5m
    max_block_bytes: 1000000
  
  # Storage configuration
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      pool:
        max_workers: 100
        queue_depth: 10000
  
  # Compactor configuration
  compactor:
    compaction:
      compaction_window: 1h
      max_compaction_objects: 1000000
      block_retention: 24h
      compacted_block_retention: 1h

# Persistence configuration
persistence:
  enabled: true
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi

# Service configuration with OTLP ports
service:
  type: ClusterIP
  port: 3100
  # Additional service configuration for OTLP
  additionalPorts:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP

# Resource configuration for local development
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 512Mi

# Ingress configuration
ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/priority: "100"
  hosts:
    - host: tempo.localhost
      paths:
        - path: /
          pathType: Prefix
  tls: []  # No TLS for local dev

# ServiceMonitor disabled for resource constraints
serviceMonitor:
  enabled: false