apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
  labels:
    app.kubernetes.io/name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/name: mysql
---
# Example ConfigMap for custom MySQL configuration (optional)
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-custom-config
  namespace: default
  labels:
    app.kubernetes.io/name: mysql
data:
  my.cnf: |
    [mysqld]
    max_connections=200
    sql_mode=STRICT_ALL_TABLES 