# 205-ollama-config.yaml
# Description:
# Deploys Ollama as a standalone service using the official Ollama Helm chart
# Configured for Apple M2 CPU (ARM64) in Rancher Desktop
# Configured to use the qwen2:0.5b model (500M parameters)
# Includes persistent storage for models
# Uses the 'ai' namespace for all resources
#
# Usage:
# Add the Ollama Helm repository:
# helm repo add ollama-helm https://otwld.github.io/ollama-helm/
# helm repo update
#
# Usage:
# installing: helm install ollama ollama-helm/ollama -f 205-ollama-config.yaml -n ai --create-namespace
# upgrading:  helm upgrade ollama ollama-helm/ollama -f 205-ollama-config.yaml -n ai
# uninstalling: helm uninstall ollama --namespace ai
#
# Debug commands:
# kubectl logs -f deployment/ollama -n ai | grep -v 'GET      "/"'
# kubectl exec -it deployment/ollama -n ai -- ollama list
# kubectl exec -it deployment/ollama -n ai -- ollama pull qwen2:0.5b
# kubectl exec -it deployment/ollama -n ai -- ollama rm model-name
# kubectl exec -it deployment/ollama -n ai -- ollama show qwen2:0.5b

# Override the name to "ollama"
fullnameOverride: "ollama"

# Specify the namespace
# Note: This won't create the namespace automatically
# Use the 'ai' namespace for all Ollama-related resources
namespaceOverride: "ai"

# Number of replicas - keeping at 1 for model consistency
replicaCount: 1

# Container resource limits optimized for M2 Mac
resources:
  requests:
    memory: 3Gi
    cpu: 1500m
  limits:
    memory: 4Gi
    cpu: 2000m

# Persistent storage for model files
persistentVolume:
  enabled: true
  existingClaim: "ollama-models"
  accessModes:
    - ReadWriteOnce
  size: 15Gi  # Size still defined but won't be used when existingClaim is set
  
# Ollama specific configuration
ollama:
  # Configure model pulling and loading at startup
  models:
    pull:
      - qwen2:0.5b
    run:
      - qwen2:0.5b
  
  # Model configuration optimized for M2 CPU
  modelConfig:
    context_length: 8192
    num_threads: 8       # M2 has 8 cores
    batch_size: 256      # Reduced for CPU processing
  
  # GPU acceleration disabled for M2
  gpu:
    enabled: false

# Service configuration to expose Ollama
service:
  type: ClusterIP
  port: 11434
  
# Adjust the probes for better stability on CPU
livenessProbe:
  enabled: true
  initialDelaySeconds: 90
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 6

readinessProbe:
  enabled: true
  initialDelaySeconds: 45
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

# Optional environment variables optimized for M2 CPU
extraEnv:
  - name: OLLAMA_HOST
    value: "0.0.0.0"
  - name: OLLAMA_COMPUTE_BACKEND
    value: "cpu"
  - name: OLLAMA_CPU_THREADS
    value: "8"
  - name: OLLAMA_BATCH_SIZE
    value: "256"

# Deployment update strategy
# Using Recreate since model loading doesn't support multiple concurrent instances well
updateStrategy:
  type: "Recreate"