# 210-openwebui-ingress.yaml
# Description: Ingress configuration for OpenWebUI using Traefik
# This is a separate ingress configuration for additional control over the ingress settings

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui
  namespace: ai
  annotations:
    traefik.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: traefik
  rules:
    - host: "openwebui.localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: open-webui
                port:
                  number: 8080 