---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-nerdmeet-test-tunnel-credentials
  namespace: default
type: Opaque
stringData:
  credentials.json: |
    {
      "AccountTag": "97e30a13fdbed4f09e53db9aba18d144",
      "TunnelSecret": "6HR7px7lVyLvi5qauV+VV7NAzA4eHffwD+Vfh6a4LDE=",
      "TunnelID": "f3170208-8a99-4edc-ac3d-7b35baa1a64c"
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-nerdmeet-test-tunnel
  namespace: default
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: cloudflare-nerdmeet-test-tunnel-config
      - name: creds
        secret:
          secretName: cloudflare-nerdmeet-test-tunnel-credentials
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-nerdmeet-test-tunnel-config
  namespace: default
data:
  config.yaml: |
    tunnel: your_tunnel_id
    credentials-file: /etc/cloudflared/creds/credentials.json
    ingress:
      - hostname: www-test.nerdmeet.org
        service: http://ingress.ingress.svc.cluster.local
      - hostname: api-test.nerdmeet.org
        service: http://ingress.ingress.svc.cluster.local
      - service: http_status:404