# net2-tailscale-host-ingress.yaml
# Template for Traefik ingress rule that routes traffic to the target service
# Creates a host-based routing rule in Traefik
#
# This template uses variables that will be replaced by the Ansible playbook:
# - {{ hostname }}: The Tailscale device hostname (e.g., "openwebui")
# - {{ tailnet }}: The Tailscale tailnet name (e.g., "dog-pence")
# - {{ service_name }}: The target Kubernetes service name
# - {{ namespace }}: The namespace where the service is located
# - {{ port }}: The port on which the service is listening
#
# Apply with: kubectl apply -f [rendered-file]

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ hostname }}-ingress"
  namespace: "{{ namespace }}"
  annotations:
    # Ensure TLS is handled properly
    traefik.ingress.kubernetes.io/ssl-redirect: "false"  # Allow both HTTP and HTTPS
    # Preserve host header for the service
    traefik.ingress.kubernetes.io/preserve-host: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: "{{ hostname }}.{{ tailnet }}.ts.net"  # Match the specific hostname
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ service_name }}"
            port:
              number: {{ port }}