# net2-tailscale-host-tunnel.yaml
# Template for Tailscale funnel ingress resource
# Creates a Tailscale device for the specified hostname that tunnels to Traefik
#
# This template uses variables that will be replaced by the Ansible playbook:
# - {{ hostname }}: The Tailscale device hostname (e.g., "openwebui")
#
# Apply with: kubectl apply -f [rendered-file]

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ hostname }}-tailscale-ingress"
  namespace: kube-system
  annotations:
    tailscale.com/funnel: "true"  # Enables public internet access via Tailscale Funnel
    tailscale.com/tags: "tag:k8s"  # Explicitly define tags
    tailscale.com/expose-metrics: "true"  # Expose metrics for monitoring
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: traefik
      port:
        number: 80  # Match Traefik's HTTP port
  tls:
    - hosts:
        - "{{ hostname }}"  # This will be the Tailscale device name