---
# u05-copy-selected-secret-keys.yml
#
# Reusable Ansible task to copy selected keys from a Kubernetes secret in one namespace to another.
#
# Usage (example):
#   - import_tasks: utility/u05-copy-selected-secret-keys.yml
#     vars:
#       source_secret_name: urbalurba-secrets
#       source_secret_namespace: default
#       target_secret_name: urbalurba-secrets
#       target_secret_namespace: ai
#       selected_keys:
#         - PGPASSWORD
#         - PGHOST
#
- name: Get source secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ source_secret_name }}"
    namespace: "{{ source_secret_namespace }}"
  register: source_secret

- name: Set fact for selected keys (Jinja2/Ansible 2.x compatible)
  set_fact:
    selected_secret_data: "{{ selected_secret_data | default({}) | combine({ item: source_secret.resources[0].data[item] }) }}"
  loop: "{{ selected_keys }}"
  when: item in source_secret.resources[0].data

- name: Create secret in target namespace with selected keys
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ target_secret_name }}"
        namespace: "{{ target_secret_namespace }}"
      type: Opaque
      data: "{{ selected_secret_data }}" 