name: 📦 Zip and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  zip-folders:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📦 Archive dev_containers folders
        run: |
          zip -r dev_containers.zip .devcontainer .devcontainer.extend

      - name: 🗑️ Delete existing release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: ⬆️ Upload dev_containers.zip as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev_containers
          path: dev_containers.zip

      - name: 🔖 Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: latest
          name: DevContainers
          draft: false
          prerelease: false
          files: dev_containers.zip