name: 📦 Zip and Upload Infrastructure Artifacts

on:
  push:
    branches:
      - main

jobs:
  zip-folders:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📦 Archive infrastructure files
        run: |
          zip -r urbalurba-infrastructure.zip . -x "terchris/*" ".github/*"

      - name: 🗑️ Delete existing release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: ⬆️ Upload infrastructure.zip as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: urbalurba-infrastructure
          path: urbalurba-infrastructure.zip

      - name: 🔖 Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: latest
          name: Infrastructure
          draft: false
          prerelease: false
          files: urbalurba-infrastructure.zip