name: 📦 Zip and Upload Infrastructure Artifacts

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  zip-folders:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Archive infrastructure files
        run: |
          zip -r urbalurba-infrastructure.zip . -x "terchris/*" ".github/*" ".git/*"

      - name: ⬆️ Upload infrastructure.zip as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: urbalurba-infrastructure
          path: urbalurba-infrastructure.zip

      - name: 🔖 Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Infrastructure v${{ github.run_number }}
          draft: false
          prerelease: false
          files: urbalurba-infrastructure.zip